trigger:
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'  # Change this to 8 or 17 if needed
      jdkArchitecture: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-B'
    displayName: 'Run Maven Tests'

  - script: |
      sudo apt-get update
      sudo apt-get install -y google-chrome-stable
    displayName: 'Install Chrome'

  - script: |
      echo "Checking if chromedriver is available..."
      chromedriver --version || echo "Install chromedriver manually if required"
    displayName: 'Check ChromeDriver'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      testRunTitle: 'Java Selenium Tests'
    condition: succeededOrFailed()
